# Server
server.port=8080

# MariaDB
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# CORS
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-imo8ajj3agklzl8n.us.auth0.com/
#logging.level.org.springframework.security=DEBUG
