# Server
server.port=8080

# MariaDB
spring.datasource.url=jdbc:mariadb://58ea917d-11a0-4864-979f-34a7070d9edc.ma.bw-cloud-instance.org:3307/plantable-test?useUnicode=true&characterEncoding=utf8&serverTimezone=Europe/Berlin
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=plantable1
spring.datasource.password=P0NlZjlRS06SeAUW

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
# auth0
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-imo8ajj3agklzl8n.us.auth0.com/
#logging.level.org.springframework.security=DEBUG
