# Server
server.port=8080

# H2 Datenbank (Datei)
spring.datasource.url=jdbc:h2:mem:plantable
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Web-Konsole (zum Anschauen der Daten)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# auth0 configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://dev-imo8ajj3agklzl8n.us.auth0.com/
# auskommentieren, um zusätzliches Logging für Spring Security zu bekommen
#logging.level.org.springframework.security=DEBUG
#logging.level.com.okta.spring=DEBUG